import { Colors } from "@sizer/musicui";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{
        height: "100vh",
        margin: 0,
        backgroundColor: Colors.Gray300,
      }} className={inter.className}>{children}</body>
    </html>
  );
}
